# Safety Security and License Configuration file
security: # configuration for the `safety check` command
  ignore-vulnerabilities: # Here you can list multiple specific vulnerabilities you want to ignore (optionally for a time period)
    33026:
      reason: Flask-Caching uses pickle, exposing a vulnerability
    42969:
      reason: The affected code is not used in pytest https://github.com/pytest-dev/pytest/issues/10392
