version: '3'

services:
  web:
    build: .
    image: master-image
    container_name: web
    ports:
      - 3000:3000
    command: sh ./runserver-github-actions-docker.sh
    logging:
      driver: 'json-file'
      options:
        max-size: '200k'
        max-file: '10'
    depends_on:
      # - postgres
      - redis
    extra_hosts:
      - 'funnel.test:127.0.0.1'
      - 'f.test:127.0.0.1'
    volumes:
      - $HOME/.aws/credentials:/app/.aws/credentials:ro
  redis:
    image: redis
  nginx:
    build:
      context: ./etc/nginx-staging
    container_name: nginx
    restart: always
    volumes:
      - static_data:/vol/static
    ports:
      - 80:80
      - 443:443
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;error_log /dev/stdout info;"'''
    depends_on:
      - web
      - postgres
  postgres:
    container_name: 'postgres'
    restart: always
    image: 'postgres:13'
    user: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      PGUSER: postgres
    volumes:
      - 'pgdata:/var/lib/postgresql/data/'
volumes:
  pgdata:
  static_data:
