# -*- coding: utf-8 -*-

from funnel.utils import extract_twitter_handle

event_ticket_types = [
    {'title': 'SpaceCon', 'ticket_types': ['Conference', 'Combo']},
    {'title': 'SpaceCon workshop', 'ticket_types': ['Workshop', 'Combo']},
]

ticket_list = [
    {
        'fullname': 'participant{id}'.format(id=str(1)),
        'email': 'participant{id}@gmail.com'.format(id=str(1)),
        'phone': '123',
        'twitter': extract_twitter_handle('@p{id}'.format(id=str(1))),
        'job_title': 'Engineer',
        'company': 'Acme',
        'city': 'Atlantis',
        'ticket_no': 't{id}'.format(id=str(1)),
        'ticket_type': 'Combo',
        'order_no': 'o{id}'.format(id=str(1)),
        'status': 'confirmed',
    },
    {
        'fullname': 'participant{id}'.format(id=str(2)),
        'email': 'participant{id}@gmail.com'.format(id=str(2)),
        'phone': '123',
        'twitter': extract_twitter_handle('@p{id}'.format(id=str(2))),
        'job_title': 'Engineer',
        'company': 'Acme',
        'city': 'Atlantis',
        'ticket_no': 't{id}'.format(id=str(2)),
        'ticket_type': 'Workshop',
        'order_no': 'o{id}'.format(id=str(2)),
        'status': 'confirmed',
    },
    {
        'fullname': 'participant{id}'.format(id=str(3)),
        'email': 'participant{id}@gmail.com'.format(id=str(3)),
        'phone': '123',
        'twitter': extract_twitter_handle('@p{id}'.format(id=str(3))),
        'job_title': 'Engineer',
        'company': 'Acme',
        'city': 'Atlantis',
        'ticket_no': 't{id}'.format(id=str(3)),
        'ticket_type': 'Conference',
        'order_no': 'o{id}'.format(id=str(3)),
        'status': 'confirmed',
    },
]

ticket_list2 = [
    {
        'fullname': 'participant{id}'.format(id=str(1)),
        'email': 'participant{id}@gmail.com'.format(id=str(1)),
        'phone': '123',
        'twitter': extract_twitter_handle('@p{id}'.format(id=str(1))),
        'job_title': 'Engineer',
        'company': 'Acme',
        'city': 'Atlantis',
        'ticket_no': 't{id}'.format(id=str(1)),
        'ticket_type': 'Combo',
        'order_no': 'o{id}'.format(id=str(1)),
        'status': 'confirmed',
    },
    {
        'fullname': 'participant{id}'.format(id=str(2)),
        'email': 'participant{id}@gmail.com'.format(id=str(2)),
        'phone': '123',
        'twitter': extract_twitter_handle('@p{id}'.format(id=str(2))),
        'job_title': 'Engineer',
        'company': 'Acme',
        'city': 'Atlantis',
        'ticket_no': 't{id}'.format(id=str(2)),
        'ticket_type': 'Workshop',
        'order_no': 'o{id}'.format(id=str(2)),
        'status': 'cancelled',
    },
    {
        'fullname': 'participant{id}'.format(id=str(3)),
        'email': 'participant{id}@gmail.com'.format(id=str(3)),
        'phone': '123',
        'twitter': extract_twitter_handle('@p{id}'.format(id=str(3))),
        'job_title': 'Engineer',
        'company': 'Acme',
        'city': 'Atlantis',
        'ticket_no': 't{id}'.format(id=str(3)),
        'ticket_type': 'Conference',
        'order_no': 'o{id}'.format(id=str(3)),
        'status': 'confirmed',
    },
]

ticket_list3 = [
    {
        'fullname': 'participant{id}'.format(id=str(1)),
        'email': 'participant{id}@gmail.com'.format(id=str(1)),
        'phone': '123',
        'twitter': extract_twitter_handle('@p{id}'.format(id=str(1))),
        'job_title': 'Engineer',
        'company': 'Acme',
        'city': 'Atlantis',
        'ticket_no': 't{id}'.format(id=str(1)),
        'ticket_type': 'Combo',
        'order_no': 'o{id}'.format(id=str(1)),
        'status': 'confirmed',
    },
    {
        'fullname': 'participant{id}'.format(id=str(2)),
        'email': 'participant{id}@gmail.com'.format(id=str(2)),
        'phone': '123',
        'twitter': extract_twitter_handle('@p{id}'.format(id=str(2))),
        'job_title': 'Engineer',
        'company': 'Acme',
        'city': 'Atlantis',
        'ticket_no': 't{id}'.format(id=str(2)),
        'ticket_type': 'Workshop',
        'order_no': 'o{id}'.format(id=str(2)),
        'status': 'cancelled',
    },
    {
        'fullname': 'participant{id}'.format(id=str(4)),
        'email': 'participant{id}@gmail.com'.format(id=str(4)),
        'phone': '123',
        'twitter': extract_twitter_handle('@p{id}'.format(id=str(4))),
        'job_title': 'Engineer',
        'company': 'Acme',
        'city': 'Atlantis',
        'ticket_no': 't{id}'.format(id=str(3)),
        'ticket_type': 'Conference',
        'order_no': 'o{id}'.format(id=str(3)),
        'status': 'confirmed',
    },
]
