"""criteria

Revision ID: 0bde7578f687
Revises: 570f4ea99cda
Create Date: 2017-04-10 23:47:16.276376

"""

# revision identifiers, used by Alembic.
revision = '0bde7578f687'
down_revision = '570f4ea99cda'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposal_space', sa.Column('criteria_html', sa.UnicodeText(), nullable=True))
    op.add_column('proposal_space', sa.Column('criteria_text', sa.UnicodeText(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proposal_space', 'criteria_text')
    op.drop_column('proposal_space', 'criteria_html')
    # ### end Alembic commands ###
