"""Added schedule

Revision ID: 1385b504ed08
Revises: 1925329c798a
Create Date: 2013-11-08 17:15:50.205187

"""

# revision identifiers, used by Alembic.
revision = '1385b504ed08'
down_revision = '1925329c798a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('description_text', sa.UnicodeText(), nullable=False),
    sa.Column('description_html', sa.UnicodeText(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=True),
    sa.Column('start_datetime', sa.DateTime(), nullable=False),
    sa.Column('end_datetime', sa.DateTime(), nullable=False),
    sa.Column('time_zone', sa.Unicode(length=30), nullable=False),
    sa.Column('proposal_space_id', sa.Integer(), nullable=False),
    sa.Column('venue_room_id', sa.Integer(), nullable=False),
    sa.Column('is_break', sa.Boolean(), nullable=False),
    sa.Column('name', sa.Unicode(length=250), nullable=False),
    sa.Column('title', sa.Unicode(length=250), nullable=False),
    sa.ForeignKeyConstraint(['proposal_space_id'], ['proposal_space.id'], ),
    sa.ForeignKeyConstraint(['venue_room_id'], ['venue_room.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name','start_datetime','end_datetime')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule')
    ### end Alembic commands ###
