"""add_badge_printed_to_participant

Revision ID: 3d5811400a38
Revises: 68d66659d3d
Create Date: 2015-04-10 17:58:29.207143

"""

# revision identifiers, used by Alembic.
revision = '3d5811400a38'
down_revision = '68d66659d3d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'name',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.add_column('participant', sa.Column('badge_printed', sa.Boolean(), nullable=True))
    op.alter_column('participant', 'email',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('participant', 'proposal_space_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sync_ticket', 'order_no',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('sync_ticket', 'ticket_no',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('ticket_type', 'name',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ticket_type', 'name',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('sync_ticket', 'ticket_no',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('sync_ticket', 'order_no',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('participant', 'proposal_space_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('participant', 'email',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.drop_column('participant', 'badge_printed')
    op.alter_column('event', 'name',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    ### end Alembic commands ###
