"""Added venue, room details

Revision ID: 423acd69b7c3
Revises: 316aaa757c8c
Create Date: 2013-11-05 17:15:01.110534

"""

# revision identifiers, used by Alembic.
revision = '423acd69b7c3'
down_revision = '316aaa757c8c'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('proposal_space_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.UnicodeText(), nullable=False),
    sa.Column('address1', sa.Unicode(length=160), nullable=False),
    sa.Column('address2', sa.Unicode(length=160), nullable=False),
    sa.Column('city', sa.Unicode(length=30), nullable=False),
    sa.Column('state', sa.Unicode(length=30), nullable=False),
    sa.Column('postcode', sa.Unicode(length=20), nullable=False),
    sa.Column('country', sa.Unicode(length=2), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=8, scale=5), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=8, scale=5), nullable=True),
    sa.Column('name', sa.Unicode(length=250), nullable=False),
    sa.Column('title', sa.Unicode(length=250), nullable=False),
    sa.ForeignKeyConstraint(['proposal_space_id'], ['proposal_space.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.UnicodeText(), nullable=False),
    sa.Column('name', sa.Unicode(length=250), nullable=False),
    sa.Column('title', sa.Unicode(length=250), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venue.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name','venue_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('room')
    op.drop_table('venue')
    ### end Alembic commands ###
