"""empty message

Revision ID: 43786857a0db
Revises: 14d1424b47
Create Date: 2015-04-06 14:19:57.934833

"""

# revision identifiers, used by Alembic.
revision = '43786857a0db'
down_revision = '14d1424b47'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_type',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=80), nullable=True),
    sa.Column('proposal_space_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['proposal_space_id'], ['proposal_space.id'], ),
    sa.PrimaryKeyConstraint('id', 'proposal_space_id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('event',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=80), nullable=True),
    sa.Column('proposal_space_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['proposal_space_id'], ['proposal_space.id'], ),
    sa.PrimaryKeyConstraint('id', 'proposal_space_id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('participant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('fullname', sa.Unicode(length=80), nullable=True),
    sa.Column('email', sa.Unicode(length=80), nullable=True),
    sa.Column('phone', sa.Unicode(length=80), nullable=True),
    sa.Column('twitter', sa.Unicode(length=80), nullable=True),
    sa.Column('job_title', sa.Unicode(length=80), nullable=True),
    sa.Column('company', sa.Unicode(length=80), nullable=True),
    sa.Column('city', sa.Unicode(length=80), nullable=True),
    sa.Column('key', sa.Unicode(length=44), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('proposal_space_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['proposal_space_id'], ['proposal_space.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('key')
    )
    op.create_table('event_ticket_type',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('ticket_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['ticket_type_id'], ['ticket_type.id'], ),
    sa.PrimaryKeyConstraint('id', 'event_id', 'ticket_type_id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('sync_ticket',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_no', sa.Unicode(length=80), nullable=True),
    sa.Column('order_no', sa.Unicode(length=80), nullable=True),
    sa.Column('ticket_type_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], ),
    sa.ForeignKeyConstraint(['ticket_type_id'], ['ticket_type.id'], ),
    sa.PrimaryKeyConstraint('id', 'ticket_type_id', 'participant_id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('ticket_no')
    )
    op.create_table('attendee',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], ),
    sa.PrimaryKeyConstraint('id', 'participant_id', 'event_id'),
    sa.UniqueConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendee')
    op.drop_table('sync_ticket')
    op.drop_table('event_ticket_type')
    op.drop_table('participant')
    op.drop_table('event')
    op.drop_table('ticket_type')
    ### end Alembic commands ###
