"""empty message

Revision ID: 43f8c3ddeca6
Revises: 43786857a0db
Create Date: 2015-04-08 15:08:46.205021

"""

# revision identifiers, used by Alembic.
revision = '43f8c3ddeca6'
down_revision = '43786857a0db'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendee', sa.Column('checked_in', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendee', 'checked_in')
    ### end Alembic commands ###
