"""empty message

Revision ID: 4676fa6fab82
Revises: 14d1424b47
Create Date: 2015-04-06 01:20:48.669351

"""

# revision identifiers, used by Alembic.
revision = '4676fa6fab82'
down_revision = '14d1424b47'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
