"""empty message

Revision ID: 4a4450eba0d5
Revises: 14d1424b47
Create Date: 2015-04-01 14:40:08.011757

"""

# revision identifiers, used by Alembic.
revision = '4a4450eba0d5'
down_revision = '14d1424b47'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_event',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=80), nullable=True),
    sa.Column('proposal_space_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['proposal_space_id'], ['proposal_space.id'], ),
    sa.PrimaryKeyConstraint('id', 'proposal_space_id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('sync_ticket_type',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=80), nullable=True),
    sa.Column('proposal_space_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['proposal_space_id'], ['proposal_space.id'], ),
    sa.PrimaryKeyConstraint('id', 'proposal_space_id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('sync_ticket',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_no', sa.Unicode(length=80), nullable=True),
    sa.Column('order_no', sa.Unicode(length=80), nullable=True),
    sa.Column('attendee_name', sa.Unicode(length=80), nullable=True),
    sa.Column('attendee_email', sa.Unicode(length=80), nullable=True),
    sa.Column('attendee_phone', sa.Unicode(length=80), nullable=True),
    sa.Column('attendee_twitter', sa.Unicode(length=80), nullable=True),
    sa.Column('attendee_job_title', sa.Unicode(length=80), nullable=True),
    sa.Column('attendee_company', sa.Unicode(length=80), nullable=True),
    sa.Column('attendee_city', sa.Unicode(length=80), nullable=True),
    sa.Column('attendee_access_key', sa.Unicode(length=44), nullable=True),
    sa.Column('sync_ticket_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sync_ticket_type_id'], ['sync_ticket_type.id'], ),
    sa.PrimaryKeyConstraint('id', 'sync_ticket_type_id'),
    sa.UniqueConstraint('attendee_access_key'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('ticket_no')
    )
    op.create_table('sync_event_ticket_type',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sync_event_id', sa.Integer(), nullable=False),
    sa.Column('sync_ticket_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sync_event_id'], ['sync_event.id'], ),
    sa.ForeignKeyConstraint(['sync_ticket_type_id'], ['sync_ticket_type.id'], ),
    sa.PrimaryKeyConstraint('id', 'sync_event_id', 'sync_ticket_type_id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('sync_attendee',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sync_ticket_id', sa.Integer(), nullable=False),
    sa.Column('sync_event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sync_event_id'], ['sync_event.id'], ),
    sa.ForeignKeyConstraint(['sync_ticket_id'], ['sync_ticket.id'], ),
    sa.PrimaryKeyConstraint('id', 'sync_ticket_id', 'sync_event_id'),
    sa.UniqueConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sync_attendee')
    op.drop_table('sync_event_ticket_type')
    op.drop_table('sync_ticket')
    op.drop_table('sync_ticket_type')
    op.drop_table('sync_event')
    ### end Alembic commands ###
