"""session speaker

Revision ID: 6f98e24760d
Revises: 58588eba8cb8
Create Date: 2013-11-22 17:28:47.751025

"""

# revision identifiers, used by Alembic.
revision = '6f98e24760d'
down_revision = '58588eba8cb8'

from alembic import op
import sqlalchemy as sa

from sqlalchemy.sql import select, bindparam
from funnel.models import Session, Proposal, User


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('speaker', sa.Unicode(length=200), nullable=True))
    ### end Alembic commands ###

    connection = op.get_bind()

    session, proposal, user = Session.__table__, Proposal.__table__, User.__table__

    result = connection.execute(select([session.c.id, user.c.fullname]).where(
        session.c.proposal_id == proposal.c.id
        and proposal.c.speaker_id == user.c.id
        ))
    sessions = [{'sid': r[0], 'speaker': r[1]} for r in result]

    updt_stmt = session.update().where(session.c.id == bindparam('sid')).values(
        speaker=bindparam('speaker'),)
    connection.execute(updt_stmt, sessions)

    connection.execute(session.update().where(session.c.speaker == None).values(speaker=u""))

    op.alter_column('session', 'speaker', nullable=False)


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'speaker')
    ### end Alembic commands ###
