"""Proposal video blogpost

Revision ID: 1195a2789872
Revises: 3c47ba103724
Create Date: 2014-02-23 02:36:49.955698

"""

# revision identifiers, used by Alembic.
revision = '1195a2789872'
down_revision = '3c47ba103724'

from alembic import op
import sqlalchemy as sa  # NOQA


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposal', sa.Column('blog_post', sa.Unicode(250), server_default=u'', nullable=False))
    op.alter_column('proposal', 'blog_post', server_default=None)
    op.add_column('proposal', sa.Column('preview_video', sa.Unicode(250), server_default=u'', nullable=False))
    op.alter_column('proposal', 'preview_video', server_default=None)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proposal', 'preview_video')
    op.drop_column('proposal', 'blog_post')
    ### end Alembic commands ###
