"""added oauth_refresh_token, oauth_expires_in and oauth_expires_at in user_externalid table

Revision ID: b7165507d80c
Revises: 0fae06340346
Create Date: 2022-03-15 15:38:33.306920

"""  # noqa

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'b7165507d80c'
down_revision = '0fae06340346'
branch_labels = None
depends_on = None


def upgrade(engine_name=''):
    # Do not modify. Edit `upgrade_` instead
    globals().get('upgrade_%s' % engine_name, lambda: None)()


def downgrade(engine_name=''):
    # Do not modify. Edit `downgrade_` instead
    globals().get('downgrade_%s' % engine_name, lambda: None)()


def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'user_externalid',
        sa.Column('oauth_refresh_token', sa.UnicodeText(), nullable=True),
    )
    op.add_column(
        'user_externalid', sa.Column('oauth_expires_in', sa.Integer(), nullable=True)
    )
    op.add_column(
        'user_externalid',
        sa.Column('oauth_expires_at', sa.TIMESTAMP(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_externalid', 'oauth_expires_at')
    op.drop_column('user_externalid', 'oauth_expires_in')
    op.drop_column('user_externalid', 'oauth_refresh_token')
    # ### end Alembic commands ###


def upgrade_geoname():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_geoname():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
