"""old pending coaster changes

Revision ID: f80ab5d0e11e
Revises: 152442fce4e4
Create Date: 2017-10-31 13:01:52.293996

"""

# revision identifiers, used by Alembic.
revision = 'f80ab5d0e11e'
down_revision = '152442fce4e4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'title',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.alter_column('sync_ticket', 'ticket_client_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ticket_type', 'title',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ticket_type', 'title',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('sync_ticket', 'ticket_client_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('event', 'title',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    # ### end Alembic commands ###
