services:
  funnel:
    build:
      context: .
    logging:
      driver: json-file
      options:
        max-size: 200k
        max-file: 10
    extra_hosts:
      - 'funnel.test:127.0.0.1'
      - 'f.test:127.0.0.1'
    environment:
      - OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
      - FLASK_RUN_HOST=0.0.0.0
