services:
  funnel:
    logging:
      driver: json-file
      options:
        max-size: 200k
        max-file: 10
    extra_hosts:
      - 'funnel.test:127.0.0.1'
      - 'f.test:127.0.0.1'
    environment:
      - FLASK_RUN_HOST=0.0.0.0
  funnel-prod:
    extends:
      file: services.yml
      service: funnel
    build:
      target: production
    links:
      - redis
