services:
  funnel:
    build:
      context: .
    image: hasgeek/funnel
    container_name: funnel
    logging:
      driver: json-file
      options:
        max-size: 200k
        max-file: 10
    extra_hosts:
      - 'funnel.test:127.0.0.1'
      - 'f.test:127.0.0.1'
