name: 'Pytest Docker'

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
    paths:
      - '**.py'
      - '**.js'
      - '**.scss'
      - '**.jinja2'
      - 'requirements/base.txt'
      - 'requirements/test.txt'
      - '.github/workflows/pytest-docker.yml'
      - 'Dockerfile'
      - 'Makefile'
      - 'pyproject.toml'
      - '.eslintrc.js'
      - 'docker-compose.yml'
      - 'docker-compose.ci.yml'
      - 'docker/entrypoints/ci.sh'
      - 'docker/initdb.sh'
      - 'package.json'
      - 'package-lock.json'
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build funnel-test image
        id: build-funnel-test
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          target: ci
          tags: funnel-ci
          load: true
          push: false
      - name: Run Tests
        run: make docker-ci-test
      - name: Upload coverage report to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: coverage/funnel.lcov
          flag-name: docker-3.11
