name: 'Pytest Docker'

on:
  push:
    paths:
      - '**.py'
      - '**.js'
      - '**.scss'
      - '**.jinja2'
      - '.flaskenv'
      - '.testenv'
      - 'requirements/base.txt'
      - 'requirements/test.txt'
      - '.github/workflows/pytest-docker.yml'
      - 'Dockerfile'
      - 'Makefile'
      - 'pyproject.toml'
      - 'docker-compose.ci.yml'
      - 'docker/entrypoints/ci.sh'
      - 'docker/initdb.sh'
      - 'package.json'
      - 'package-lock.json'
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build funnel-ci image
        id: build-funnel-ci
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          target: ci
          tags: funnel-ci
          load: true
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Set permissions for coverage
        run: docker compose -f docker-compose.ci.yml run -u root --entrypoint "" --no-deps --quiet-pull main chown -R 1000:1000 coverage
      - name: Test with pytest
        run: docker compose -f docker-compose.ci.yml up --quiet-pull --no-attach db --no-attach redis --no-log-prefix --exit-code-from main
      - name: Upload coverage report to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: coverage/funnel.lcov
          flag-name: docker-3.11
