name: Telegram Notify
on:
  issues:
    types: [opened, edited, closed, reopened, milestoned, demilestoned]
  issue_comment:
    types: [created]
  push:
  pull_request:
    types:
      # Exclude 'synchronize' as that is duplicated in the 'push' event
      [
        assigned,
        closed,
        converted_to_draft,
        edited,
        labeled,
        locked,
        opened,
        ready_for_review,
        reopened,
        review_request_removed,
        review_requested,
        unassigned,
        unlabeled,
        unlocked,
      ]
  pull_request_review:
  project:
  project_card:
    types: [created, closed, reopened, deleted]
  release:
  watch:

jobs:
  notify-all:
    if: ${{ !contains(fromJson('["issues", "issue_comment", "pull_request", "pull_request_review", "push"]'), github.event_name) }}
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          disable_web_page_preview: true
          message: |
            <b>${{ github.event_name }}</b> by ${{ github.actor }} in https://github.com/${{ github.repository }}

  issues:
    if: ${{ github.event_name == 'issues' }}
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          disable_web_page_preview: true
          message: |
            <b>${{ github.event_name }}/${{ github.event.action }}</b> by ${{ github.actor }}: ${{ github.event.issue.title }} ${{ github.event.issue.html_url }}

  issue_comment:
    if: ${{ github.event_name == 'issue_comment' }}
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          disable_web_page_preview: true
          message: |
            <b>${{ github.event_name }}/${{ github.event.action }}</b> by ${{ github.actor }} in ${{ github.event.issue.title }} ${{ github.event.issue.html_url }}:

            ${{ github.event.comment.body }} ${{ github.event.comment.html_url }}

  pull_request:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          disable_web_page_preview: true
          message: |
            <b>${{ github.event_name }}/${{ github.event.action }}</b> by ${{ github.actor }}: ${{ github.event.pull_request.title }} ${{ github.event.pull_request.html_url }}

  pull_request_review:
    if: ${{ github.event_name == 'pull_request_review' }}
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          disable_web_page_preview: true
          message: |
            <b>${{ github.event_name }}/${{ github.event.action }} (${{ github.event.review.state }})</b> by ${{ github.actor }} in ${{ github.event.pull_request.title }} ${{ github.event.pull_request.html_url }}:

            ${{ github.event.review.body }} ${{ github.event.pull_request_review.html_url }}

push:
  if: ${{ github.event_name == 'push' }}
  runs-on: ubuntu-latest
  steps:
    - uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        format: html
        disable_web_page_preview: true
        message: |
          <b>${{ github.event_name }}</b> by ${{ github.actor }} in ${{ github.repository }}: ${{ github.event.head_commit.message }} ${{ github.event.compare }}
