name: Telegram Notify
on:
  issues:
    types: [opened, edited, closed, reopened, milestoned, demilestoned]
  issue_comment:
    types: [created]
  push:
    branches: [main]
  pull_request:
  pull_request_review:
  project:
  project_card:
    types: [created, closed, reopened, deleted]
  release:
  watch:

jobs:
  notify-all:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram message (catch-all)
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            *${{ github.event_name }}* by ${{ github.actor }} in ${{ github.repository }}
