name: Telegram Notify
on:
  issues:
    types: [opened, edited, closed, reopened, milestoned, demilestoned]
  issue_comment:
    types: [created]
  push:
  pull_request:
    types:
      # Exclude 'synchronize' as that is duplicated in the 'push' event
      [
        assigned,
        closed,
        converted_to_draft,
        edited,
        labeled,
        locked,
        opened,
        ready_for_review,
        reopened,
        review_request_removed,
        review_requested,
        unassigned,
        unlabeled,
        unlocked,
      ]
  pull_request_review:
  project:
  project_card:
    types: [created, moved, converted, edited, deleted]
  release:
  watch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: kanga333/variable-mapper@master
        with:
          key: '${{ github.actor }}'
          map: |
            {
              "djamg": {"tguser": "@dj_amg"},
              "jace": {"tguser": "@jackerhack"},
              "miteshashar": {"tguser": "@miteshashar"},
              "sankarshanmukhopadhyay": {"tguser": "@sankarshan"},
              "StephanieBr": {"tguser": "@stephaniebrne"},
              "vidya-ram": {"tguser": "@vidya_ramki"},
              "zainabbawa": {"tguser": "@Saaweoh"},
              ".*": {"tguser": "Unknown"}
            }
          export_to: env

      - uses: kanga333/variable-mapper@master
        with:
          key: '${{ github.event_name }}'
          map: |
            {
                "issues": {"message":
                  "<b>${{ github.event_name }}/${{ github.event.action }}</b> by ${{ env.tguser }} (${{ github.actor }}): ${{ github.event.issue.title }} ${{ github.event.issue.html_url }}"
                },
                "issue_comment": {"message":
                  "<b>${{ github.event_name }}/${{ github.event.action }}</b> by ${{ env.tguser }} (${{ github.actor }}) in ${{ github.event.issue.title }} ${{ github.event.issue.html_url }}:\n\n${{ github.event.comment.body }} ${{ github.event.comment.html_url }}"
                },
                "pull_request": {"message":
                  "<b>${{ github.event_name }}/${{ github.event.action }}</b> by ${{ env.tguser }} (${{ github.actor }}): ${{ github.event.pull_request.title }} ${{ github.event.pull_request.html_url }}"
                },
                "pull_request_review": {"message":
                  "<b>${{ github.event_name }}/${{ github.event.action }} (${{ github.event.review.state }})</b> by ${{ env.tguser }} (${{ github.actor }}) in ${{ github.event.pull_request.title }} ${{ github.event.pull_request.html_url }}:\n\n${{ github.event.review.body }} ${{ github.event.review.html_url }}"
                },
                "push": {"message":
                  "<b>${{ github.event_name }}</b> by ${{ env.tguser }} (${{ github.actor }}) in ${{ github.repository }}: ${{ github.event.head_commit.message }} ${{ github.event.compare }}"
                },
                ".*": {"message":
                  "<b>${{ github.event_name }}</b> by ${{ env.tguser }} (${{ github.actor }}) in https://github.com/${{ github.repository }}"
                }
              }
          export_to: env

      - uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          disable_web_page_preview: true
          message: '${{ env.message }}'
