language: python
python:
  - "3.7"
services:
  - redis-server
  - postgresql
install:
  - pip install git+https://github.com/hasgeek/flask-babelhg/
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt
before_script:
  - psql -c 'create database lastuser_test_app;' -U postgres
script:
  - ./runtests.sh
after_success:
  - coveralls
notifications:
  email: false
